[gdb/python] Don't use import *
While reviewing a python patch I noticed this in __init__.py:
...
 # Note that two indicators are needed here to silence flake8.
 from _gdb import *  # noqa: F401,F403
...
as well as this in disassembler.py:
...
 # Re-export everything from the _gdb.disassembler module, which is
 # defined within GDB's C++ code.  Note that two indicators are needed
 # here to silence flake8.
 from _gdb.disassembler import *  # noqa: F401,F403
...
where F403 is the flake8 error:
...
'from module import *' used; unable to detect undefined names
...

I wondered whether I could get rid of the F403 warning.

As a first step, I used gdb to generate an equivalent but concrete import:
...
from _gdb import (  # noqa: F401
    ARCH_FRAME,
    BP_ACCESS_WATCHPOINT,
    ...
    target_wide_charset,
    write,
)
...

That got me a new warning:
...
$ pre-commit run flake8 --all-files
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

__init__.py:317:5: F811 redefinition of unused 'flush' from line 36
__init__.py:320:5: F811 redefinition of unused 'write' from line 36
...

This complains about a redefinition of flush/write as imported from _gdb, but
the new definition is actually of _GdbFile.write and _GdbFile.flush, so I
think this warning is incorrect.  Ignore this using "noqa: F811".

Then I realized there's a risk of the import list and the _gdb module to get
out of sync.

So I've added a check:
...
gdb._util.verify_import_all("_gdb", globals())
...
to make sure that if for instance I drop ARCH_FRAME from the import list, I
get:
...
$ gdb -q -batch -ex "python import gdb"
Missing: from _gdb import ARCH_FRAME
Python Exception <class 'AssertionError'>:
...

Do the same for disassembler.py.

Add new file _util.py as private module to be able to access verify_import_all
from both files.

Tested on aarch64-linux.

[1] https://www.flake8rules.com/rules/F403.html