gdb-rhbz2424325-c23-more-const-fixes.patch
;; Backport Keith Seitz's C23 const-correctness fixes (pending upstream review).
;; Mailing list: https://sourceware.org/pipermail/binutils/2026-January/...
;; Posted 2026-01-07, not yet approved.

Fix some more C23 const-correctness issues

Fedora Rawhide is failing to build due to new glibc header changes
enforcing const-correctness in functions like strchr and memchr.
For example:

../../opcodes/aarch64-dis.c: In function ‘remove_dot_suffix’:
../../opcodes/aarch64-dis.c:4027:7: error: assignment discards ‘const’ qualifier from po
inter target type [-Werror=discarded-qualifiers]
 4027 |   ptr = strchr (inst->opcode->name, '.');
      |       ^
cc1: all warnings being treated as errors

This patch addresses all the discovered issues with --enable-targets=all
and regenerates a few cgen files along the way.