[gdb/testsuite, Tcl 9.0] Fix Tcl version check
With Tcl 9.0, we get:
...
ERROR: tcl error sourcing tool init file lib/gdb.exp.
version conflict for package "Tcl": have 9.0.2, need 8.6.2
version conflict for package "Tcl": have 9.0.2, need 8.6.2
    while executing
"package require Tcl 8.6.2"
    (file "lib/gdb.exp" line 20)
...

Fix this by using tcl_version_at_least.

Bug: https://sourceware.org/bugzilla/show_bug.cgi?id=33948