[gdb] Declare gdb_get_ncolors
Since a recent commit, I run into:
....
gdb/ui-style.c: In lambda function:
gdb/ui-style.c:597:20: error: ‘gdb_get_ncolors’ was not declared in this scope
  597 |       int colors = gdb_get_ncolors ();
      |                    ^~~~~~~~~~~~~~~
make: *** [Makefile:2096: ui-style.o] Error 1
....

Fix this by adding the missing declaration.