[gdb/testsuite, Tcl 9.0] Fix deprecated trace variable subcommand
With Tcl 9.0, we get:
...
bad option "variable": must be add, info, or remove
    while executing
"trace variable "boards_dir" w append_gdb_boards_dir"
    (file "lib/append_gdb_boards_dir.exp" line 48)
...

Indeed "trace variable" is for backwards compatibility, and "deprecated and
will likely be removed in a future version of Tcl" [1].

Fix this by using "trace add variable".

This gets us:
...
ERROR: tcl error sourcing build/gdb/testsuite/site.exp.
bad operation "w": must be array, read, unset, or write
    while executing
"trace add variable "boards_dir" w append_gdb_boards_dir"
...
which is fixed by using "write" instead of "w".

Bug: https://sourceware.org/bugzilla/show_bug.cgi?id=33948

[1] https://www.tcl-lang.org/man/tcl8.4/TclCmd/trace.htm#M27