[gdb/build] Fix Wformat errors in gdb/riscv-tdep.c
When building gdb with --enable-targets=all on arm-linux, I run into:
...
gdb/riscv-tdep.c: In function ‘bool try_read(regcache*, int, ULONGEST&)’:
gdb/riscv-tdep.c:4887:18: error: format ‘%lx’ expects argument of type \
  ‘long unsigned int’, but argument 2 has type ‘ULONGEST’ \
  {aka ‘long long unsigned int’} [-Werror=format=]
 4887 |       warning (_("Can not read at address %lx"), addr);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
and a few more Wformat errors, due to commit b9c7eed0c24 ("This commit adds
record full support for rv64gc instruction set").

Fix these by using hex_string.

Tested by completing a build on arm-linux.